apps:
  - name: api
    script: dotnet run
    cwd: ../Pacco.APIGateway/src/Pacco.APIGateway
    max_restarts: 3
  - name: availability
    script: dotnet run
    cwd: ../Pacco.Services.Availability/src/Pacco.Services.Availability.Api
    max_restarts: 3
  - name: customers
    script: dotnet run
    cwd: ../Pacco.Services.Customers/src/Pacco.Services.Customers.Api
    max_restarts: 3
  - name: deliveries
    script: dotnet run
    cwd: ../Pacco.Services.Deliveries/src/Pacco.Services.Deliveries.Api
    max_restarts: 3
  - name: identity
    script: dotnet run
    cwd: ../Pacco.Services.Identity/src/Pacco.Services.Identity.Api
    max_restarts: 3
  - name: operations
    script: dotnet run
    cwd: ../Pacco.Services.Operations/src/Pacco.Services.Operations.Api
    max_restarts: 3
  - name: orders
    script: dotnet run
    cwd: ../Pacco.Services.Orders/src/Pacco.Services.Orders.Api
    max_restarts: 3
  - name: parcels
    script: dotnet run
    cwd: ../Pacco.Services.Parcels/src/Pacco.Services.Parcels.Api
    max_restarts: 3
  - name: pricing
    script: dotnet run
    cwd: ../Pacco.Services.Pricing/src/Pacco.Services.Pricing.Api
    max_restarts: 3
  - name: vehicles
    script: dotnet run
    cwd: ../Pacco.Services.Vehicles/src/Pacco.Services.Vehicles.Api
    max_restarts: 3