version: "3.5"

services:
  api-gateway:
    image: devmentors/pacco.apigateway
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada-async.docker.yml
    ports:
      - 5000:5000
    networks:
      - pacco

  availability-service:
    image: devmentors/pacco.services.availability
    container_name: availability-service
    restart: unless-stopped
    ports:
      - 5001:5000 
    networks:
      - pacco

  customers-service:
    image: devmentors/pacco.services.customers
    container_name: customers-service
    restart: unless-stopped
    ports:
      - 5002:5000
    networks:
      - pacco

  deliveries-service:
    image: devmentors/pacco.services.deliveries
    container_name: deliveries-service
    restart: unless-stopped
    ports:
      - 5003:5000
    networks:
      - pacco

  identity-service:
    image: devmentors/pacco.services.identity
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5004:5000
    networks:
      - pacco

  operations-service:
    image: devmentors/pacco.services.operations
    container_name: operations-service
    restart: unless-stopped
    ports:
      - 5005:5000
    networks:
      - pacco

  orders-service:
    image: devmentors/pacco.services.orders
    container_name: orders-service
    restart: unless-stopped
    ports:
      - 5006:5000
    networks:
      - pacco
    depends_on:
      - availability-service
      - customers-service
      - deliveries-service
      - identity-service
      - orders-service
      - ordermaker-service
      - parcels-service
      - vehicles-service

  ordermaker-service:
    image: devmentors/pacco.services.ordermaker
    container_name: ordermaker-service
    restart: unless-stopped
    ports:
      - 5015:5000
    networks:
      - pacco

  parcels-service:
    image: devmentors/pacco.services.parcels
    container_name: parcels-service
    restart: unless-stopped
    ports:
      - 5007:5000
    networks:
      - pacco

  pricing-service:
    image: devmentors/pacco.services.pricing
    container_name: pricing-service
    restart: unless-stopped
    ports:
      - 5008:5000
    networks:
      - pacco

  vehicles-service:
    image: devmentors/pacco.services.vehicles
    container_name: vehicles-service
    restart: unless-stopped
    ports:
      - 5009:5000
    networks:
      - pacco

networks:
  pacco:
    name: pacco-network
    external: true